#!/usr/bin/python3

import cgi,cgitb
import os
from responses_html.response_html import ResponseHtml
from orm.orm import Orm

if __name__ == "__main__" :
    html = ResponseHtml()
    if os.environ['REQUEST_METHOD'] == 'POST':
        form = cgi.FieldStorage()
        try:
            lista_usuarios_encontrados = Orm.searchUserList(form)
            html.set_http_response_busqueda_usuario(lista_usuarios_encontrados)
        except Exception as e:
            html.set_http_alert(e.__str__(), "danger")
            html.set_http_response_busqueda_usuario()
        html.render()
    else:
        html.set_http_response_busqueda_usuario()
        html.render()