#!/usr/bin/python3


import cgi,cgitb
import csv
import os
from responses_html.response_html import ResponseHtml
from orm.orm import Orm


if __name__ == "__main__" :
    html = ResponseHtml()
    if os.environ['REQUEST_METHOD'] == 'POST':
        form =cgi.FieldStorage()
        rango = form.getvalue("select_rango")
        lista_usuarios_en_rango = Orm.searchUsersInRange(rango)
        if lista_usuarios_en_rango:
            html.set_http_response_busqueda_usuarios_en_rango(lista_usuarios_en_rango)
        else:
            html.set_http_response_busqueda_usuarios_en_rango()
            html.set_http_alert("No se encontro ningun usuario en el rango especificado", "danger")
        html.render()
    else:
        html.set_http_response_rango_edades()
        html.render()