#!/usr/bin/python3

import cgi,cgitb
import csv
import os
from http import cookies
import time, hashlib
from responses_html.response_html import ResponseHtml
from orm.orm import Orm


def crear_cookie():
    cookie = cookies.SimpleCookie()
    # The sid will be a hash of the server time
    sid = hashlib.md5(repr(time.time()).encode()).hexdigest()
    # Set the sid in the cookie
    cookie["sid"] = sid
    # Will expire in a year
    cookie["sid"]["expires"] = 12 * 30 * 24 * 60 * 60
    return cookie


def get_token_from_cookie(string_cookie, cookie_existente=None):
    """
    Metodo que devuelve el token asociado a la cookie completa
    """
    if cookie_existente: #Ya viene creada la cookie
        return cookie_existente["sid"].value 
    # obtengo la cookie del querystring
    cookie = cookies.SimpleCookie()
    cookie.load(string_cookie)
    return cookie["sid"].value #Token de cookie


def login(html):
    """
    Ademas de loguear debe setear una cookie para el usuario
    """
    cgitb.enable()
    form = cgi.FieldStorage()
    legajo = form.getvalue("legajo") #Busqueda por campo clave: legajo
    pwd = form.getvalue("pwd")
    cookie = crear_cookie()

    if (Orm.searchUser(legajo, pwd)):
        html.setCookie(cookie) #Seteo nueva cookie
        token = get_token_from_cookie(None, cookie) #Asocio token de cookie a usuario en tokenfile
        Orm.saveTokenInTokenfile(legajo, pwd, token)
        html.redirect("modificar_usuario")
    else:
        html.set_http_response_login()
        html.render()
    

if __name__ == "__main__" :
    html = ResponseHtml()
    string_cookie = os.environ.get('HTTP_COOKIE')
    if string_cookie: #Si hay una cookie entonces veo si corresponde en el archivo
        token = get_token_from_cookie(string_cookie)
        if Orm.findTokenInTokenFile(token):
            #Levanto la cookie
            cookie = cookies.SimpleCookie()
            cookie.load(string_cookie)
            html.setCookie(cookie)
            html.redirect("modificar_usuario")
        else: #Sesion vencida
            login(html)
    else: #No hay cookie entonces hay que loguear
        login(html)
   


