#!/usr/bin/python3


import cgi,cgitb
import csv
import os
from http import cookies
from responses_html.response_html import ResponseHtml
from orm.orm import Orm


if __name__ == "__main__" :

    html = ResponseHtml()
    string_cookie = os.environ.get('HTTP_COOKIE')

    if string_cookie: #Si hay una cookie entonces veo si corresponde en el archivo
        cookie = cookies.SimpleCookie()
        cookie.load(string_cookie)
        token = cookie['sid'].value

        if Orm.findTokenInTokenFile(token):
            html.setCookie(cookie) #para seguir trabajando con la cookie
            legajo = Orm.getUserFromTokenfile(token)
            datos_usuario = Orm.getDatosUsuario(legajo)
            form = cgi.FieldStorage()

            if "boton_submit_modificacion" in form: #Si modifico los datos los pido de nuevo en la linea de abajo (es un refresh)

                Orm.modificateUser(legajo, form)

                datos_usuario = Orm.getDatosUsuario(legajo)
                html.set_http_response_moficacion_usuario(datos_usuario)
                html.set_http_alert("Usuario modificado correctamente","success")
                html.render()
            else:
                html.set_http_response_moficacion_usuario(datos_usuario)
                html.render()
        else:
            #Cookie vencida o invalida
            html.set_http_alert("Cookie vencia o invalida", "danger")
            html.redirect("login")
    else:
        #no hay cookie
        html.redirect("login")