#!/usr/bin/python3

import cgi,cgitb
import os
from responses_html.response_html import ResponseHtml
from orm.orm import Orm
from datetime import datetime, timedelta
from http import cookies
import time, hashlib
from datetime import datetime


if __name__ == "__main__" :
    html = ResponseHtml()
    string_cookie = os.environ.get('HTTP_COOKIE')

    if string_cookie: #Si hay una cookie entonces veo si corresponde en el archivo
        cookie = cookies.SimpleCookie()
        cookie.load(string_cookie)
        token = None
        try:
            token = cookie['sid'].value
        except:
            pass
        
        if Orm.findTokenInTokenFile(token):
            timestamp = datetime.now().strftime("%m/%d/%Y %H:%M:%S")
            nick = Orm.getUserFromTokenfile(token)
            lista_usuarios_en_vivo = Orm.getUsuariosEnVivo()
            lista_nuevos_mensajes = Orm.getNuevosMensajes(nick,timestamp)

            cookie['timestamp'] = timestamp
            html.setCookie(cookie)
            html.set_http_response_sala_de_chat(lista_usuarios_en_vivo, lista_nuevos_mensajes, nick)
            html.render()
        else:
            #Cookie vencida o invalida
            html.redirect("login")
    else:
        #no hay cookie
        html.redirect("login")




