#!/usr/bin/python3

import cgi,cgitb
import os
from responses_html.response_html import ResponseHtml
from orm.orm import Orm
from http import cookies
from datetime import datetime

if __name__ == '__main__':
    html = ResponseHtml()
    string_cookie = os.environ.get('HTTP_COOKIE')
    if string_cookie: #Si hay una cookie entonces veo si corresponde en el archivo

        cookie = cookies.SimpleCookie()
        cookie.load(string_cookie)
        token = None
        try:
            token = cookie['sid'].value
        except:
            pass
        
        if Orm.findTokenInTokenFile(token):
            form = cgi.FieldStorage()

            mensaje = form.getvalue("mensaje") 
            nick = Orm.getUserFromTokenfile(token)
            timestamp = datetime.now().strftime("%m/%d/%Y %H:%M:%S")

            Orm.guardarNuevoMensaje(nick, mensaje, timestamp)
            #Orm.actualizarUltimoIngreso(timestamp, nick)

            #cookie['timestamp'] = timestamp
            html.setCookie(cookie) 
                   
            html.render()

        else: #Sesion vencida
            pass
            #html.set_http_alert("Cookie vencida. Reintente", "danger")
            #html.redirect('login')
    else: #No hay cookie entonces hay que loguear
        html.redirect('login')




