#!/usr/bin/python3

import cgi,cgitb
import os
from responses_html.response_html import ResponseHtml
from orm.orm import Orm
from http import cookies
from datetime import datetime
import json

if __name__ == '__main__':
    html = ResponseHtml()
    string_cookie = os.environ.get('HTTP_COOKIE')
    if string_cookie: #Si hay una cookie entonces veo si corresponde en el archivo

        cookie = cookies.SimpleCookie()
        cookie.load(string_cookie)
        token = None
        try:
            token = cookie['sid'].value
        except:
            pass
        if Orm.findTokenInTokenFile(token):
            form = cgi.FieldStorage()
            nick = Orm.getUserFromTokenfile(token)
            timestamp = cookie['timestamp'].value
            lista_usuarios_en_vivo = Orm.getUsuariosEnVivo()
            lista_nuevos_mensajes = Orm.getNuevosMensajes(nick,timestamp)
            if lista_nuevos_mensajes:
                cookie['timestamp'] = datetime.now().strftime("%m/%d/%Y %H:%M:%S")
            html.setCookie(cookie)
            html.set_ajax_response(json.dumps({'lista_nuevos_mensajes':lista_nuevos_mensajes,
                                                'lista_usuarios_en_vivo':lista_usuarios_en_vivo }))
            html.render()
        else: 
            #Sesion vencida
            html.set_ajax_response(json.dumps({'lista_nuevos_mensajes':[],
                                                'lista_usuarios_en_vivo':[]}))
            html.render()
    else: 
        #No hay cookie entonces hay que loguear
        html.setContentBody("")
        html.render()